schema = 3

[mod]
  [mod."github.com/go-logfmt/logfmt"]
    version = "v0.6.0"
    hash = "sha256-RtIG2qARd5sT10WQ7F3LR8YJhS8exs+KiuUiVf75bWg="
  [mod."github.com/godror/godror"]
    version = "v0.41.0"
    hash = "sha256-lHqSjrY8l+GsKk9kYDr+1rwP6N2mqrvottFP3Q5+iDA="
  [mod."github.com/godror/knownpb"]
    version = "v0.1.1"
    hash = "sha256-tblRsuYD9AD/vDH+3ZkuR5Ua6t9cNfdOQ0a/Zl5v+OE="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240119083558-1b970713d09a"
    hash = "sha256-JQ3JLywTjgboNhs12blhOkS3ty7m8sUa/zaWv1k/X28="
  [mod."golang.org/x/sync"]
    version = "v0.1.0"
    hash = "sha256-Hygjq9euZ0qz6TvHYQwOZEjNiTbTh1nSLRAWZ6KFGR8="
  [mod."google.golang.org/protobuf"]
    version = "v1.32.0"
    hash = "sha256-GJuTkMGHCzHbyK4yD5kY4oMn8wQWqgkeBK//yVDqHJk="
